Create Insertionsort
malivinayak/Multi-Programming pull request #54
Opened 2022-10-19 04:51 UTC by akhilmishra365

added code for insertion sort

2022-10-19 11:06 UTC, malivinayak requested changes
Update README.md and I will merge the PR

2022-10-19 14:17 UTC, akhilmishra365 commented
> Update README.md and I will merge the PR

done!

2022-10-19 14:17 UTC, akhilmishra365 reviewed
Updated Readme.md

2022-10-19 14:19 UTC, akhilmishra365 reviewed
Updated Readme.md

2022-10-19 14:39 UTC, malivinayak commented on Program_Category/03 Algorithm/Sorting Algorithms/Insertionsort
> +// C++ program for insertion sort
put this file inside appropriate folder

2022-10-19 14:52 UTC, akhilmishra365 commented
Thanks buddy this is my first time in hacktober fest thanks for making me
learn

On Wed, 19 Oct, 2022, 20:11 malivinayak, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Please follow appropriate structure to make successful PR
>
> You have to also update this README
> <https://github.com/akhilmishra365/Multi-Programming/tree/patch-1/Program_Category/03%20Algorithm>
> File too
>
> This is not for me
> I am doing this so that you can learn to contribute properly
> ------------------------------
>
> In Program_Category/03 Algorithm/Sorting Algorithms/README.md
> <https://github.com/malivinayak/Multi-Programming/pull/54#discussion_r999556975>
> :
>
> > @@ -4,3 +4,4 @@
>  4. [Radial Sort](./Radial%20Sort/)
>  5. [Topological Sort](./Topological%20Sort/)
>  6. [Heap Sort](./Heap%20Sort/)
> +7. [Insertionsort](./Insertionsort%20/)
>
> link is broken
>
> This is right one
>
> 7. [Insertionsort](./Insertionsort/)
>
> ------------------------------
>
> In Program_Category/03 Algorithm/Sorting Algorithms/Insertionsort
> <https://github.com/malivinayak/Multi-Programming/pull/54#discussion_r999557808>
> :
>
> > @@ -0,0 +1,50 @@
> +// C++ program for insertion sort
>
> put this file inside appropriate folder
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/malivinayak/Multi-Programming/pull/54#pullrequestreview-1147725634>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVATP6ISFTIMIAWXM7JUWVLWEACBPANCNFSM6AAAAAARIXDHFM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-19 15:19 UTC, akhilmishra365 reviewed
fILE MOVED TO SPECIFIC FOLDER

2022-10-19 15:20 UTC, akhilmishra365 commented on Program_Category/03 Algorithm/Sorting Algorithms/README.md
> +7. [Insertionsort](./Insertionsort%20/)
UPDATED ALL THE README FILES

2022-10-19 15:31 UTC, malivinayak commented
> Thanks buddy this is my first time in hacktober fest thanks for making me learn...........

You can ask me things you don't know as you are new

2022-10-19 15:45 UTC, akhilmishra365 commented
Ok sir ,
Currently I have done all the requested changes please have a review and
let me know your feedback that's very important for me ☺️

On Wed, 19 Oct, 2022, 21:01 malivinayak, ***@***.***> wrote:

> Thanks buddy this is my first time in hacktober fest thanks for making me
> learn...........
>
> You can ask me things you don't know as you are new
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/malivinayak/Multi-Programming/pull/54#issuecomment-1284202267>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVATP6PABRTYAWMZVE7GWMLWEAH5NANCNFSM6AAAAAARIXDHFM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-19 17:49 UTC, akhilmishra365 reviewed
ALL CHANGES DONE

2022-10-20 02:01 UTC, malivinayak approved these changes

2022-10-20 02:04 UTC, malivinayak commented
Everything is perfect now
Now you know how someone request changes and approves it in PR

Thank You for your patience as well as contibution

Rewards Tip ~ You can also create multiple PR in same repo which will counted as a valid PR towards hacketoberfest

2022-10-20 02:04 UTC, merged